---
# handlers file for agent
- name: Restart Jenkins
  ansible.builtin.systemd:
    name: jenkins
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Reload Systemd Daemon
  ansible.builtin.command:
    cmd: systemctl daemon-reload    

- name: install-new-plugins
  ansible.builtin.command: >
    /usr/bin/java -jar {{ plugin_manager.file_path }}
    --plugin-file {{ jenkins.home_dir }}/plugins.txt
    --jenkins-version 2.528.1
    --plugin-download-directory {{ jenkins.plugins_dir }}
    --verbose
  notify: Restart Jenkins