---
# handlers file for agent
- name: Restart Jenkins
  ansible.builtin.systemd:
    name: jenkins
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Reload Systemd Daemon
  ansible.builtin.command:
    cmd: systemctl daemon-reload    