jobs:
  - script: |
      freeStyleJob('seed-job') {
        description('Seed job quản lý các Jenkins jobs bằng Job DSL')
        label('built-in')

        scm {
          git {
            remote {
              url('https://github.com/tuan0919/bestarion-jenkins-personal.git')
              credentials('github-key')
            }
            branch('main')
          }
        }

        steps {
          dsl {
            external('jenkins_home/casc/jobs/dsl/**/*.groovy')
            removeAction('DELETE')
          }
        }

        logRotator {
          numToKeep(10)
        }

        properties {
          disableConcurrentBuilds()
        }

        triggers {
          githubPush()
        }
      }
