pipeline {
    agent { label 'built-in' }
    environment {
        WORKSPACE = "${env.JENKINS_MASTER_HOME_DIRECTORY}/workspace/casc-pipeline"
        JENKINS_CASC_DIR = "${env.JENKINS_MASTER_HOME_DIRECTORY}/casc"
    }
    stages {
        stage('Validate JCasC syntax') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jenkins-api-user', usernameVariable: 'JENKINS_USER', passwordVariable: 'JENKINS_PASSWORD')]) {
                    sh '''
                set -e

                for file in $(find $WORKSPACE/jenkins_home/casc -type f -name '*.yaml'); do
                    echo -e "🔍 Checking: $file"
                    cat $file | /usr/local/bin/jenkins-cmd.sh \
                        -auth $JENKINS_USER:$JENKINS_PASSWORD \
                        check-configuration 2> /tmp/err.txt
                    if [ $? -ne 0 ]; then
                        echo -e "❌ Validation failed for $file"
                        echo "------ Error Details ------"
                        cat /tmp/err.txt
                        echo "----------------------------"
                        exit 1
                    else
                        echo -e "✅ Validation succeeded for $file"
                    fi
                done
                '''
                }
            }
        }

        stage('Deploy new JCasC files') {
            steps {
                sh '''
                echo "Deploying validated YAMLs to $JENKINS_CASC_DIR ..."
                rm -rf $JENKINS_CASC_DIR/*
                cp -rf $WORKSPACE/jenkins_home/casc/* $JENKINS_CASC_DIR/
                ls -l $JENKINS_CASC_DIR
                '''
            }
        }

        stage('Apply JCasC configuration') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jenkins-api-user', usernameVariable: 'JENKINS_USER', passwordVariable: 'JENKINS_PASSWORD')]) {
                    sh '''
                    set -e

                    echo "Apply new JCasC Configuration"
                        /usr/local/bin/jenkins-cmd.sh \
                        -auth $JENKINS_USER:$JENKINS_PASSWORD \
                        reload-jcasc-configuration

                    if [ $? -ne 0 ]; then
                        echo "❌ Failed to apply JCasC configuration"
                        exit 1
                    else
                        echo "✅ JCasC configuration applied successfully"
                    fi
                    '''
                }
            }
        }
    }
}
